[build-system]
requires = [
    "setuptools >= 60.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "f1_udp_socket"
version = "0.0.1"
dependencies = [
    "python-docx",
]
requires-python = ">=3.10"
